dist: bionic
sudo: required
language: bash

cache:
  timeout: 900
  directories:
    - $HOME/cache

branches:
  only:
    - master

arch:
  - arm64

env:
  - DOCKER_IMAGES="26.3-dev 26.3" DOCKER_EXPERIMENTAL=enabled

install:
  - sudo bin/prepare-docker
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes || echo 'ARMNONEED'
  - cd 26.3/dev
  - setarch $(uname -m) -R docker build --pull --platform arm64 -t "silex/emacs:26.3-test-arm64" .
  - setarch $(uname -m) -R docker build --pull --platform arm -t "silex/emacs:26.3-test-arm32" .

notifications:
  email:
    on_success: never
    on_failure: never
